project:
  type: website
  output-dir: docs

website:
  title: "Python프로그래밍"
  bread-crumbs: false
  navbar:
    left:
      - href: 1_python.qmd
        text: Python
      - text: Basic
        menu:
          - href: 2_1_basic.qmd
            text: (1) 기초 문법
          - href: 2_2_conditional.qmd
            text: (2) 조건문
          - href: 2_3_loop.qmd
            text: (3) 반복문
          - href: 2_4_function.qmd
            text: (4) 함수
          - href: 2_5_string.qmd
            text: (5) 문자열
      - text: Data Structure
        menu:
          - href: 3_1_structure.qmd
            text: (1) 자료구조
          - href: 3_2_list.qmd
            text: (2) 리스트
          - href: 3_3_tuple.qmd
            text: (3) 튜플
          - href: 3_4_set.qmd
            text: (4) 세트
          - href: 3_5_dictionary.qmd
            text: (5) 딕셔너리
      - text: Library
        menu:
          - href: 4_1_numpy.qmd
            text: (1) NumPy
          - href: 4_2_pandas.qmd
            text: (2) Pandas

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
    toc-location: right
    toc-expand: true

