project:
  type: website
  output-dir: docs

website:
  title: "Python프로그래밍"
  bread-crumbs: false
  navbar:
    left:
      - href: 1_python.qmd
        text: Python
      - text: Basic
        menu:
          - href: 2_1_basic.qmd
            text: (1) 기초 문법
          - href: 2_2_conditional.qmd
            text: (2) 조건문
          - href: 2_3_loop.qmd
            text: (3) 반복문

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true
    toc-location: right
    toc-expand: true

